@host = http://localhost

Get {{host}}/api

###

Post {{host}}/search
content-type: application/json

{
    "text": "nvda"
}

###


Post {{host}}/candles
content-type: application/json

{
    "symbol": "nvda",
    "interval": "5"
}