@host = http://localhost:3000
//@host = https://trading-lounge-data-api-brlocky.vercel.app/
// @host = https://tradingloungedataapi.onrender.com


Get {{host}}/api

###

Post {{host}}/search
content-type: application/json

{
    "text": "nvda"
}

###


Post {{host}}/candles
content-type: application/json

{
    "symbol": "nvda",
    "interval": "M"
}


### 


Post {{host}}/chat
content-type: application/json

{
    "prompt": "Hello"
}



###


Post {{host}}/candles
content-type: application/json

{
    "symbol": "NASDAQ:AAPL",
    "interval": "1h"
}


### 


Get {{host}}/candles?symbol=INDEX:SPX&interval=1h
content-type: application/json

 
### 


Post {{host}}/quotes
content-type: application/json

{
    "symbols": [
        "INDEX:SPX",
        "NASDAQ:AAPL",
        "NASDAQ:TSLA",
        "INDEX:NDX",
        "ASX:BHP",
        "ASX:CBA"
        ]
}



### 


Post https://trading-view-data-byd5tqbtwa-uc.a.run.app/search
content-type: application/json

{
    "query": "aapl"
}

### 




GET {{host}}/search?query=nvda
content-type: application/json

###

GET {{host}}/search?query=aapl
content-type: application/json