@host = http://localhost:3000
//@host = https://trading-lounge-data-api-brlocky.vercel.app/
// @host = https://tradingloungedataapi.onrender.com


Get {{host}}/api

###

Post {{host}}/search
content-type: application/json

{
    "text": "nvda"
}

###


Post {{host}}/candles
content-type: application/json

{
    "symbol": "nvda",
    "interval": "M"
}


### 


Post {{host}}/chat
content-type: application/json

{
    "prompt": "Hello"
}


### 




Get {{host}}/search?query=nvda
 
###



Get {{host}}/search?query=aapl
 
###


Get {{host}}/search?query=spx
 
###


Get {{host}}/search?query=spy
 
###


Post {{host}}/candles
content-type: application/json

{
    "symbol": "NASDAQ:AAPL",
    "interval": "1h"
}


### 


Post {{host}}/candles
content-type: application/json

{
    "symbol": "INDEX:SPX",
    "interval": "1h"
}

### 


Post {{host}}/quotes
content-type: application/json

{
    "symbols": [
        "INDEX:SPX",
        "NASDAQ:AAPL",
        ]
}